//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionPersonnelMedicale.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionPersonnelMedicale.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Consultation.
        /// </summary>
        internal static string Ajouter_Consultation {
            get {
                return ResourceManager.GetString("Ajouter Consultation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Department.
        /// </summary>
        internal static string Ajouter_Département {
            get {
                return ResourceManager.GetString("Ajouter Département", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Nurses.
        /// </summary>
        internal static string Ajouter_Infirmiers {
            get {
                return ResourceManager.GetString("Ajouter Infirmiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Doctors.
        /// </summary>
        internal static string Ajouter_Médecins {
            get {
                return ResourceManager.GetString("Ajouter Médecins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string Anglais {
            get {
                return ResourceManager.GetString("Anglais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultations.
        /// </summary>
        internal static string Consultations {
            get {
                return ResourceManager.GetString("Consultations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Départements {
            get {
                return ResourceManager.GetString("Départements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string Francais {
            get {
                return ResourceManager.GetString("Francais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nurses.
        /// </summary>
        internal static string Infirmiers {
            get {
                return ResourceManager.GetString("Infirmiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string Médecins {
            get {
                return ResourceManager.GetString("Médecins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string Prêt {
            get {
                return ResourceManager.GetString("Prêt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Management System.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
